//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DentalMedical.Web.sys_logs {
    
    
    /// <summary>
    /// Add 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Add 
    {
        
		protected global::System.Web.UI.WebControls.TextBox txtLogsType;
		protected global::System.Web.UI.WebControls.TextBox txtEntity;
		protected global::System.Web.UI.WebControls.TextBox txtincident;
		protected global::System.Web.UI.WebControls.TextBox txtIP;
		protected global::System.Web.UI.WebControls.TextBox txtclientInfo;
		protected global::System.Web.UI.WebControls.TextBox txtlogmessage;
		protected global::System.Web.UI.WebControls.TextBox txtorderId;
		protected global::System.Web.UI.WebControls.TextBox txtcreateDate;
		protected global::System.Web.UI.WebControls.TextBox txtmodifyDate;
		protected global::System.Web.UI.WebControls.TextBox txtflag;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
