//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DentalMedical.Web.simple_EMR {
    
    
    /// <summary>
    /// Modify 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Modify {
        	protected global::System.Web.UI.WebControls.Label lblId;
	protected global::System.Web.UI.WebControls.Label lblEMR_Code;
		protected global::System.Web.UI.WebControls.TextBox txtpatient_Name;
		protected global::System.Web.UI.WebControls.TextBox txtpatient_Age;
		protected global::System.Web.UI.WebControls.TextBox txtpatient_Sex;
		protected global::System.Web.UI.WebControls.TextBox txtpatient_Tel;
		protected global::System.Web.UI.WebControls.TextBox txtpatient_WeChatCode;
		protected global::System.Web.UI.WebControls.TextBox txtmain_suit;
		protected global::System.Web.UI.WebControls.TextBox txtallergy_history;
		protected global::System.Web.UI.WebControls.TextBox txtMedical_history;
		protected global::System.Web.UI.WebControls.TextBox txttherapeutic_schedule;
		protected global::System.Web.UI.WebControls.TextBox txtdoctorRemark;
		protected global::System.Web.UI.WebControls.TextBox txtcRemark;
		protected global::System.Web.UI.WebControls.TextBox txtemr_status;
		protected global::System.Web.UI.WebControls.TextBox txtconfirm_time;
		protected global::System.Web.UI.WebControls.TextBox txtprocessing_time;
		protected global::System.Web.UI.WebControls.TextBox txtprocessing_requirement;
		protected global::System.Web.UI.WebControls.TextBox txtorder_time;
		protected global::System.Web.UI.WebControls.TextBox txtpay_time;
		protected global::System.Web.UI.WebControls.TextBox txtproduction_time;
		protected global::System.Web.UI.WebControls.TextBox txtdelivery_time;
		protected global::System.Web.UI.WebControls.TextBox txtend_time;
		protected global::System.Web.UI.WebControls.TextBox txtcreateDate;
	protected global::System.Web.UI.WebControls.Label lblcreateId;
		protected global::System.Web.UI.WebControls.TextBox txtmodifyDate;
	protected global::System.Web.UI.WebControls.Label lblmodifyId;
		protected global::System.Web.UI.WebControls.TextBox txtflag;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
