//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DentalMedical.Web.simple_EMR {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblId;
	protected global::System.Web.UI.WebControls.Label lblEMR_Code;
	protected global::System.Web.UI.WebControls.Label lblpatient_Name;
	protected global::System.Web.UI.WebControls.Label lblpatient_Age;
	protected global::System.Web.UI.WebControls.Label lblpatient_Sex;
	protected global::System.Web.UI.WebControls.Label lblpatient_Tel;
	protected global::System.Web.UI.WebControls.Label lblpatient_WeChatCode;
	protected global::System.Web.UI.WebControls.Label lblmain_suit;
	protected global::System.Web.UI.WebControls.Label lblallergy_history;
	protected global::System.Web.UI.WebControls.Label lblMedical_history;
	protected global::System.Web.UI.WebControls.Label lbltherapeutic_schedule;
	protected global::System.Web.UI.WebControls.Label lbldoctorRemark;
	protected global::System.Web.UI.WebControls.Label lblcRemark;
	protected global::System.Web.UI.WebControls.Label lblemr_status;
	protected global::System.Web.UI.WebControls.Label lblconfirm_time;
	protected global::System.Web.UI.WebControls.Label lblprocessing_time;
	protected global::System.Web.UI.WebControls.Label lblprocessing_requirement;
	protected global::System.Web.UI.WebControls.Label lblorder_time;
	protected global::System.Web.UI.WebControls.Label lblpay_time;
	protected global::System.Web.UI.WebControls.Label lblproduction_time;
	protected global::System.Web.UI.WebControls.Label lbldelivery_time;
	protected global::System.Web.UI.WebControls.Label lblend_time;
	protected global::System.Web.UI.WebControls.Label lblcreateDate;
	protected global::System.Web.UI.WebControls.Label lblcreateId;
	protected global::System.Web.UI.WebControls.Label lblmodifyDate;
	protected global::System.Web.UI.WebControls.Label lblmodifyId;
	protected global::System.Web.UI.WebControls.Label lblflag;


       
    }
}
