//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DentalMedical.Web.factory {
    
    
    /// <summary>
    /// Add 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Add 
    {
        
		protected global::System.Web.UI.WebControls.TextBox txtfactoryCode;
		protected global::System.Web.UI.WebControls.TextBox txtfactoryTel;
		protected global::System.Web.UI.WebControls.TextBox txtfactoryPwd;
		protected global::System.Web.UI.WebControls.TextBox txtfactoryEmail;
		protected global::System.Web.UI.WebControls.TextBox txtfactoryKey;
		protected global::System.Web.UI.WebControls.TextBox txtfactoryLogo;
		protected global::System.Web.UI.WebControls.TextBox txtonlineStatus;
		protected global::System.Web.UI.WebControls.TextBox txtfactoryName;
		protected global::System.Web.UI.WebControls.TextBox txtfee;
		protected global::System.Web.UI.WebControls.TextBox txtinvit_code;
		protected global::System.Web.UI.WebControls.TextBox txtorderId;
		protected global::System.Web.UI.WebControls.TextBox txtfactoryRemark;
		protected global::System.Web.UI.WebControls.TextBox txtcreateDate;
		protected global::System.Web.UI.WebControls.TextBox txtmodifyDate;
		protected global::System.Web.UI.WebControls.TextBox txtflag;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
