//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DentalMedical.Web.factory_certification {
    
    
    /// <summary>
    /// Modify 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Modify {
        	protected global::System.Web.UI.WebControls.Label lblId;
	protected global::System.Web.UI.WebControls.Label lblfactory_Id;
		protected global::System.Web.UI.WebControls.TextBox txtlegal_Person;
		protected global::System.Web.UI.WebControls.TextBox txtorganization_Code;
		protected global::System.Web.UI.WebControls.TextBox txtmain_Person;
		protected global::System.Web.UI.WebControls.TextBox txtmain_Tel;
		protected global::System.Web.UI.WebControls.TextBox txtbusiness_license;
		protected global::System.Web.UI.WebControls.TextBox txtLegal_ID;
		protected global::System.Web.UI.WebControls.TextBox txtfactory_Address;
		protected global::System.Web.UI.WebControls.TextBox txtmedical_license;
		protected global::System.Web.UI.WebControls.TextBox txtinstrument_license;
		protected global::System.Web.UI.WebControls.TextBox txtstatus;
		protected global::System.Web.UI.WebControls.TextBox txtorderId;
		protected global::System.Web.UI.WebControls.TextBox txtcreateDate;
	protected global::System.Web.UI.WebControls.Label lblcreateId;
		protected global::System.Web.UI.WebControls.TextBox txtmodifyDate;
	protected global::System.Web.UI.WebControls.Label lblmodifyId;
		protected global::System.Web.UI.WebControls.TextBox txtflag;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
