//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DentalMedical.Web.factory_certification {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblId;
	protected global::System.Web.UI.WebControls.Label lblfactory_Id;
	protected global::System.Web.UI.WebControls.Label lbllegal_Person;
	protected global::System.Web.UI.WebControls.Label lblorganization_Code;
	protected global::System.Web.UI.WebControls.Label lblmain_Person;
	protected global::System.Web.UI.WebControls.Label lblmain_Tel;
	protected global::System.Web.UI.WebControls.Label lblbusiness_license;
	protected global::System.Web.UI.WebControls.Label lblLegal_ID;
	protected global::System.Web.UI.WebControls.Label lblfactory_Address;
	protected global::System.Web.UI.WebControls.Label lblmedical_license;
	protected global::System.Web.UI.WebControls.Label lblinstrument_license;
	protected global::System.Web.UI.WebControls.Label lblstatus;
	protected global::System.Web.UI.WebControls.Label lblorderId;
	protected global::System.Web.UI.WebControls.Label lblcreateDate;
	protected global::System.Web.UI.WebControls.Label lblcreateId;
	protected global::System.Web.UI.WebControls.Label lblmodifyDate;
	protected global::System.Web.UI.WebControls.Label lblmodifyId;
	protected global::System.Web.UI.WebControls.Label lblflag;


       
    }
}
