//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DentalMedical.Web.hospitals {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblId;
	protected global::System.Web.UI.WebControls.Label lblhospitalName;
	protected global::System.Web.UI.WebControls.Label lblhospitalEName;
	protected global::System.Web.UI.WebControls.Label lblhospitalCode;
	protected global::System.Web.UI.WebControls.Label lblhospitalAddress;
	protected global::System.Web.UI.WebControls.Label lblhospitalTel;
	protected global::System.Web.UI.WebControls.Label lblhospitalWeb;
	protected global::System.Web.UI.WebControls.Label lblhospitalIntroduction;
	protected global::System.Web.UI.WebControls.Label lblorderId;
	protected global::System.Web.UI.WebControls.Label lblcreateDate;
	protected global::System.Web.UI.WebControls.Label lblcreateId;
	protected global::System.Web.UI.WebControls.Label lblmodifyDate;
	protected global::System.Web.UI.WebControls.Label lblmodifyId;
	protected global::System.Web.UI.WebControls.Label lblflag;


       
    }
}
