//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DentalMedical.Web.doctors {
    
    
    /// <summary>
    /// Add 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Add 
    {
        
		protected global::System.Web.UI.WebControls.TextBox txtuserCode;
		protected global::System.Web.UI.WebControls.TextBox txtuserTel;
		protected global::System.Web.UI.WebControls.TextBox txtuserPwd;
		protected global::System.Web.UI.WebControls.TextBox txtuserEmail;
		protected global::System.Web.UI.WebControls.TextBox txtuserKey;
		protected global::System.Web.UI.WebControls.TextBox txtuserPetName;
		protected global::System.Web.UI.WebControls.TextBox txtuserLogo;
		protected global::System.Web.UI.WebControls.TextBox txtuserRealName;
		protected global::System.Web.UI.WebControls.TextBox txtuserAddress;
		protected global::System.Web.UI.WebControls.TextBox txtuserWorkYears;
		protected global::System.Web.UI.WebControls.TextBox txtuserSchool;
		protected global::System.Web.UI.WebControls.TextBox txtuserBlog;
		protected global::System.Web.UI.WebControls.TextBox txtonlineStatus;
		protected global::System.Web.UI.WebControls.TextBox txtf_invit_code;
		protected global::System.Web.UI.WebControls.TextBox txtorderId;
		protected global::System.Web.UI.WebControls.TextBox txtdoctor_Id;
		protected global::System.Web.UI.WebControls.TextBox txtuserRemark;
		protected global::System.Web.UI.WebControls.TextBox txtcreateDate;
		protected global::System.Web.UI.WebControls.TextBox txtmodifyDate;
		protected global::System.Web.UI.WebControls.TextBox txtflag;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
