//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DentalMedical.Web.doctors {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblId;
	protected global::System.Web.UI.WebControls.Label lbluserCode;
	protected global::System.Web.UI.WebControls.Label lbluserTel;
	protected global::System.Web.UI.WebControls.Label lbluserPwd;
	protected global::System.Web.UI.WebControls.Label lbluserEmail;
	protected global::System.Web.UI.WebControls.Label lbluserKey;
	protected global::System.Web.UI.WebControls.Label lbluserPetName;
	protected global::System.Web.UI.WebControls.Label lbluserLogo;
	protected global::System.Web.UI.WebControls.Label lbluserRealName;
	protected global::System.Web.UI.WebControls.Label lbluserAddress;
	protected global::System.Web.UI.WebControls.Label lbluserWorkYears;
	protected global::System.Web.UI.WebControls.Label lbluserSchool;
	protected global::System.Web.UI.WebControls.Label lbluserBlog;
	protected global::System.Web.UI.WebControls.Label lblonlineStatus;
	protected global::System.Web.UI.WebControls.Label lblf_invit_code;
	protected global::System.Web.UI.WebControls.Label lblorderId;
	protected global::System.Web.UI.WebControls.Label lbldoctor_Id;
	protected global::System.Web.UI.WebControls.Label lbluserRemark;
	protected global::System.Web.UI.WebControls.Label lblcreateDate;
	protected global::System.Web.UI.WebControls.Label lblcreateId;
	protected global::System.Web.UI.WebControls.Label lblmodifyDate;
	protected global::System.Web.UI.WebControls.Label lblmodifyId;
	protected global::System.Web.UI.WebControls.Label lblflag;


       
    }
}
