//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DentalMedical.Web.logistics_info {
    
    
    /// <summary>
    /// Modify 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Modify {
        	protected global::System.Web.UI.WebControls.Label lblId;
	protected global::System.Web.UI.WebControls.Label lblfactory_Id;
		protected global::System.Web.UI.WebControls.TextBox txtEMR_Code;
	protected global::System.Web.UI.WebControls.Label lbldsId;
		protected global::System.Web.UI.WebControls.TextBox txtexpressName;
		protected global::System.Web.UI.WebControls.TextBox txtexpress_billCode;
		protected global::System.Web.UI.WebControls.TextBox txtcRemark;
		protected global::System.Web.UI.WebControls.TextBox txtorderId;
		protected global::System.Web.UI.WebControls.TextBox txtcreateDate;
	protected global::System.Web.UI.WebControls.Label lblcreateId;
		protected global::System.Web.UI.WebControls.TextBox txtmodifyDate;
	protected global::System.Web.UI.WebControls.Label lblmodifyId;
		protected global::System.Web.UI.WebControls.TextBox txtflag;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
