//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DentalMedical.Web.logistics_info {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblId;
	protected global::System.Web.UI.WebControls.Label lblfactory_Id;
	protected global::System.Web.UI.WebControls.Label lblEMR_Code;
	protected global::System.Web.UI.WebControls.Label lbldsId;
	protected global::System.Web.UI.WebControls.Label lblexpressName;
	protected global::System.Web.UI.WebControls.Label lblexpress_billCode;
	protected global::System.Web.UI.WebControls.Label lblcRemark;
	protected global::System.Web.UI.WebControls.Label lblorderId;
	protected global::System.Web.UI.WebControls.Label lblcreateDate;
	protected global::System.Web.UI.WebControls.Label lblcreateId;
	protected global::System.Web.UI.WebControls.Label lblmodifyDate;
	protected global::System.Web.UI.WebControls.Label lblmodifyId;
	protected global::System.Web.UI.WebControls.Label lblflag;


       
    }
}
